# Generated by Django 5.1.3 on 2024-12-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Beneficio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Beneficio')),
                ('value_per_meal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por refeição')),
                ('quantity_of_meals', models.PositiveIntegerField(verbose_name='Quantidade de refeições')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportationVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Beneficio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Beneficio')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
