# Generated by Django 5.1.3 on 2024-12-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportationvoucher',
            options={'verbose_name': 'Vale Transporte', 'verbose_name_plural': 'Vales Transporte'},
        ),
    ]
