# Generated by Django 5.1.3 on 2024-12-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0002_alter_transportationvoucher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealvoucher',
            options={'verbose_name': 'Vale Refeição', 'verbose_name_plural': 'Vales Refeições'},
        ),
    ]
