# Generated by Django 5.1.3 on 2024-12-02 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0003_alter_mealvoucher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Beneficio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Beneficio')),
            ],
            options={
                'verbose_name': 'Benefício Base',
                'verbose_name_plural': 'Benefícios Base',
            },
        ),
        migrations.RemoveField(
            model_name='mealvoucher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mealvoucher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mealvoucher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transportationvoucher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transportationvoucher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transportationvoucher',
            name='name',
        ),
        migrations.AddField(
            model_name='mealvoucher',
            name='benefitbase_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benefit.benefitbase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationvoucher',
            name='benefitbase_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benefit.benefitbase'),
            preserve_default=False,
        ),
    ]
