# Generated by Django 5.1.3 on 2024-12-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0004_benefitbase_remove_mealvoucher_description_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitbase',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='benefitbase',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
