# Generated by Django 5.1.3 on 2024-12-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0006_alter_benefitbase_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitbase',
            name='info_extra',
            field=models.TextField(default=1, verbose_name='Informações extras'),
            preserve_default=False,
        ),
    ]
